#!/bin/bash
#------------------------------------------------
# On MIC setup script to run multiple tasks/MIC
#
# 11/27/2012 - l.wilson
#
# Texas Advanced Computing Center
# The University of Texas at Austin
#------------------------------------------------

#Calculate the number of processor based on number of hosts and wayness of the job
export TACC_LAUNCHER_NPROCS=$(($TACC_LAUNCHER_NPHI * $TACC_LAUNCHER_PHI_PPN))
export TACC_LAUNCHER_ON_PHI=1

for i in `seq 0 $(($TACC_LAUNCHER_PHI_PPN - 1))`
do
  #Start the launcher script for every process to be spawned on this host and give it a unique task id
  $TACC_LAUNCHER_DIR/launcher $(($TACC_LAUNCHER_PHI_PPN * $TACC_LAUNCHER_PHI_ID + $i)) $* &
done
