#!/bin/bash
#------------------------------------------------
# On MIC setup script to run multiple tasks/MIC
#
# 11/27/2012 - l.wilson
#
# Texas Advanced Computing Center
# The University of Texas at Austin
#------------------------------------------------

#Calculate the number of processor based on number of hosts and wayness of the job
export LAUNCHER_NPROCS=$(($LAUNCHER_NPHI * $LAUNCHER_PHI_PPN))
export LAUNCHER_ON_PHI=1

for i in `seq 0 $(($LAUNCHER_PHI_PPN - 1))`
do
  #Start the launcher script for every process to be spawned on this host and give it a unique task id
  $LAUNCHER_DIR/launcher $(($LAUNCHER_PHI_PPN * $LAUNCHER_PHI_ID + $i)) $* &
done
