#!/bin/bash
#------------------------------------------------
# Simple serial job launcher for TACC systems 
#
# 9/9/2006 - l.wilson
# 1/21/2011 - l.wilson - Modified to spawn only
#                        1 ssh/host
# 7/11/2012 - l.wilson - Added scheduling options
# 11/30/2012 - l.wilson - Added Xeon Phi support
#
# Texas Advanced Computing Center
# The University of Texas at Austin
#------------------------------------------------

LAUNCHER_TSK_ID=$1

if [ "$LAUNCHER_ON_PHI" == "1" ];then
  cd $5
  export INFILE="$6"
else
  cd $2
  export INFILE="$3"
fi

export LAUNCHER_NJOBS=`cat $INFILE | wc -l`

if [ "$LAUNCHER_ON_PHI" == "1" ];then
  LAUNCHER_DYN_SRV="$LAUNCHER_PHI_DYN_COUNT"
else
  LAUNCHER_DYN_SRV="$LAUNCHER_DYN_COUNT"
fi

if [ "$LAUNCHER_TSK_ID" == "0" ];then

  if [ "$LAUNCHER_PN_PHI" == "1" ];then
    echo "--------------------------------------------------"
    echo "Launcher (on Intel Xeon Phi) -> $LAUNCHER_NPROCS processors allocated."
    echo "Launcher (on Intel Xeon Phi) -> $LAUNCHER_NJOBS total tasks to complete."
    echo "--------------------------------------------------"
    echo " "
  else
    echo "--------------------------------------------------"
    echo "Launcher -> $LAUNCHER_NPROCS processors allocated."
    echo "Launcher -> $LAUNCHER_NJOBS total tasks to complete."
    echo "--------------------------------------------------"
    echo " "
  fi
else
    sleep 0.5
fi

#---------------------------------
# Setup initial JID for each task
#---------------------------------
if [ $LAUNCHER_SCHED == "interleaved" ]; then
  # Setup stride for assigning serial tasks
  export LAUNCHER_JID=`expr $LAUNCHER_TSK_ID + 1`
elif [ $LAUNCHER_SCHED == "block" ]; then
  blocks=`expr $LAUNCHER_NJOBS / $LAUNCHER_NPROCS`
  if [ `expr $blocks \* $LAUNCHER_NPROCS` -lt $LAUNCHER_NJOBS ]; then
    blocks=`expr $blocks + 1`
  fi
  export LAUNCHER_JID=`expr $LAUNCHER_TSK_ID \* $blocks + 1`
  nextblock=`expr \( $LAUNCHER_TSK_ID + 1 \) \* $blocks + 1`
else
  # Grab the JID to run from The Count
  export LAUNCHER_JID=`telnet $LAUNCHER_DYN_SRV 2>/dev/null | grep -v -e "^Connected" -e "Trying" -e "Escape"`
fi 

COMPLETE="false"

while [ $COMPLETE == "false" ]; do
  export CMD=`grep -m $LAUNCHER_JID . $INFILE | tail -n 1`
  echo "TACC Launcher -> Initiating task $LAUNCHER_JID on `hostname` ($CMD)"
  eval $CMD
  if [ $LAUNCHER_SCHED == "interleaved" ]; then
    export LAUNCHER_JID=`expr $LAUNCHER_JID + $LAUNCHER_NPROCS`
    if [ $LAUNCHER_JID -gt $LAUNCHER_NJOBS ]; then
      COMPLETE="true"
    fi
  elif [ $LAUNCHER_SCHED == "block" ]; then
    export LAUNCHER_JID=`expr $LAUNCHER_JID + 1`
    if [ $LAUNCHER_JID -ge $nextblock ]; then
      COMPLETE="true"
    fi
  else
    export LAUNCHER_JID=`telnet $LAUNCHER_DYN_SRV 2>/dev/null | grep -v -e "^Connected" -e "Trying" -e "Escape"`
    if [ $LAUNCHER_JID == "" ]; then
      COMPLETE="true"
    fi
  fi
done
