#!/bin/sh

echo "TACC: Starting up job $JOB_ID"

# Get the PE hostfile, number of slots and wayness from the environment
pe_hostfile=$PE_HOSTFILE
pe_slots=$NSLOTS
pe_ppn=`echo $PE | sed -e 's/way//g;'`

if [ x"$LAUNCHER_PPN" == "x" ]; then
  export LAUNCHER_PPN=$pe_ppn
fi

srq_size=2048
default_time_out=23
  
# Find out which MPI stack we're using
MODE=`/sge_common/default/pe_scripts/getmode.sh`

# Set our files and directories
home_sge_dir="$HOME/.sge"
if [ ! -d $home_sge_dir ]; then
  mkdir -p $home_sge_dir
fi
hostfile_tacc=`mktemp $home_sge_dir/job.$JOB_ID.hostlist.XXXXXXXX`
nslotsfile_tacc=`mktemp $home_sge_dir/job.$JOB_ID.info.XXXXXXXX`

if [ -f $nslotsfile_tacc ]; then
  rm $nslotsfile_tacc
fi

if [ -f $hostfile_tacc ]; then
  rm $hostfile_tacc
fi

for i in `cat $pe_hostfile | cut -f 1 -d ' '`; do
  echo $i >> $hostfile_tacc
done
np=`cat $hostfile_tacc | wc -l`

echo "TACC: Setup complete. Running job script."

if [ x"$MY_NSLOTS" == "x" ]; then
  if [ -f $nslotsfile_tacc ]; then
    MY_NSLOTS=`cat $nslotsfile_tacc`
  else
    MY_NSLOTS=$NSLOTS
  fi
fi

#------------------
# Scheduling setup
#------------------
if [ $LAUNCHER_SCHED == "dynamic" ]; then
  #Start The Count
  $LAUNCHER_DIR/tskserver `wc -l $WORKDIR/$CONTROL_FILE` 9471 2>/dev/null &
  export LAUNCHER_DYN_COUNT="$HOSTNAME 9471"
  if [ $LAUNCHER_NPHI -ne "0" ]; then
    #Start another server for the Intel Xeon Phi cards
    $LAUNCHER_DIR/tskserver `wc -l $PHI_WORKDIR/$PHI_CONTROL_FILE` 9472 2>/dev/null &
    export LAUNCHER_PHI_DYN_COUNT="$HOSTNAME 9472"
  fi
fi

#------------------------------
# Let's finally launch the job
#------------------------------

echo "Launcher: starting parallel tasks..."

i=0
for host in `cat $hostfile_tacc`
do
  ssh $host "cd `pwd`; env `/sge_common/default/pe_scripts/build_env.pl` LAUNCHER_NHOSTS=$np LAUNCHER_HOST_ID=$i $*" &
  i=`expr $i + 1`
done
wait

res=$?

if [ $res -ne 0 ]; then
  echo "Launcher: Parametric job exited with code: $res"
else
  echo "Launcher: Parametric job exited without errors"
fi

exit $res
