#!/usr/bin/env python

try:
  import socketserver
except ImportError:
  import SocketServer as socketserver

import sys

(major, minor)=sys.version_info[:2]
if major<=2 and minor < 7:
  print("ERROR: Python version 2.7 or better required")
  sys.exit(1)

num=1
maxnum=int(sys.argv[1])
port=int(sys.argv[3])

class TCPIntHandler(SocketServer.BaseRequestHandler):
  def handle(self):
    global num
    global server
    global maxnum
    if num > maxnum:
      self.request.sendall(bytes("Done", "utf-8"))
    else:
      self.request.sendall(bytes(str(num), "utf-8"))
      num+=1

server = SocketServer.TCPServer((sys.argv[2], port), TCPIntHandler)

server.request_queue_size=100000
server.serve_forever()
