#!/usr/bin/env python

try:
  import socketserver as SocketServer

  def prepare_str(s):
    # convert str s to bytes when using Python 3
    return bytes(s, "utf-8")

except ImportError:
  import SocketServer

  def prepare_str(s):
    # no conversion required when using Python 2
    return s

import sys

(major, minor)=sys.version_info[:2]
if major<=2 and minor < 7:
  print("ERROR: Python version 2.7 or better required")
  sys.exit(1)

num=1
maxnum=int(sys.argv[1])
port=int(sys.argv[3])

class TCPIntHandler(SocketServer.BaseRequestHandler):
  def handle(self):
    global num
    global server
    global maxnum
    if num > maxnum:
      self.request.sendall(prepare_str("Done"))
    else:
      self.request.sendall(prepare_str(str(num)))
      num+=1

server = SocketServer.TCPServer((sys.argv[2], port), TCPIntHandler)

server.request_queue_size=100000
server.serve_forever()
