#!/usr/bin/env python

import SocketServer
import sys

num=1
maxnum=int(sys.argv[1])
port=int(sys.argv[3])

class TCPIntHandler(SocketServer.BaseRequestHandler):
  def handle(self):
    global num
    global server
    global maxnum
    if num > maxnum:
      self.request.sendall("Done")
    else:
      self.request.sendall("{}".format(num))
      num+=1

server = SocketServer.TCPServer((sys.argv[2], port), TCPIntHandler)

server.serve_forever()
