#!/bin/bash

# Usually the launcher directory is defined in the LAUNCHER_DIR env. var.

                   # If command line argument exists, use it as the launcher directory.
[[ ! -z "$1" ]] && export LAUNCHER_DIR=$1

                   # if LAUNCHER_DIR is not defined, use one directory above
if [[ -z "$LAUNCHER_DIR" ]]; then
    export LAUNCHER_DIR=../
fi

export LAUNCHER_JOB_FILE=commands
export LAUNCHER_SCHED=interleaved
export LAUNCHER_WORKDIR=`pwd`

$LAUNCHER_DIR/paramrun
